package petrinets;

public enum ModelAction {
	LOAD_FILE, PRINT_LINE, UPDATE_PLACE, UPDATE_TRANSITION, ADD_ARC, ADD_PLACE, ADD_TRANSITION, ADD_MARKING, HIGHLIGHT_MARKING, ADD_EDGE,
	HIGHLIGHT_EDGE, SET_SECOND_OMEGA_MARKING, SET_FIRST_OMEGA_MARKING, SET_OMEGA_PATH, HIGHLIGHT_PLACE
}
