package petrinets.controller;

public enum ButtonActions {
	OPEN_FILE, RESET, CHOOSE_MULTIPLE_DATA, RESET_PETRINET, CLEAR_MARKING_GRAPH, PLUS_TOKEN, MINUS_TOKEN, ANALYSE_GRAPH, PETRINET_CLICK, MARKING_GRAPH_CLICK
	
}
